### ISSUE TITLE
Window object not defined when accessing MyAlgo Wallet from Next.js SSR project

### ISSUE THREAD

**Issue by daoarchitect** [randlabs/communication-bridge#5]
The window object is not defined when instantiating a new instance of the MyAlgo class, even if a `typeof window !== 'undefined'` check is done beforehand on the client side. I think all calls to `window` should be wrapped in a similar check in case the Communication Bridge is accessed from the server side.

**Comment by daoarchitect** [comment]
I should mention, I've opened this issue on the communication-bridge repo because the error I was thrown was coming from line 144 in the lib/messenger.js file when the `message` event listener is added to the `window` object.

**Comment by mxmauro** [comment]
Hi @daoarchitect the bridge is not intended to be used from a backend or server-side rendering.

Can you give us some background on the project and why the code is loaded in the server side portion?

**Comment by daoarchitect** [comment]
Hey @mxmauro, looks like this was a Next.js-specific. I solved it by loading the component that was using the MyAlgo class dynamically using Next.js's [Dynamic Import](https://nextjs.org/docs/advanced-features/dynamic-import) feature.

**Comment by scottbolasevich** [comment]
@0xTsubi any chance you could share that fix im facing the same issue and im familar with the dynamic Import just wondering where exactly you made that change

**Comment by scottbolasevich** [comment]
i agree with this.. can you please update the messanger.js and wrap it like this.. its super annoying to keep adding it back in and it works good / as needed

> 		if (typeof window !== "undefined") {
> 			window.addEventListener("message", this._listener);
> 		}

**Comment by scottbolasevich** [comment]
ty!!!!
